### ISSUE TITLE
設定の「変換」箇所の設定変更ができない

### ISSUE THREAD

**Issue by nC2nico** [xpadev-net/niconicomments-convert#111]
「設定」タブ内の「変換」という箇所のvalueの値を変更できません。
(C:\Users\ユーザー名\AppData\Roaming\niconicomments-convert\config.jsonの中身を設定する箇所です)
入力カーソルは出てきますが、どの文字を入力しようとしても反映されず、またback space,deleteキー等による文字の削除もできません。
(keyの値は変更できます)
また、key,value入力欄の追加ボタンを押して新たに追加される行に文字を入力しようとするとアプリケーションが灰色一色になり操作できなくなります。(key,valueどちらの入力欄でも同じです)
この現象が発生した後にアプリケーションを再起動させるとkey,valueの値が崩れてしまいます。
例：
デフォルト状態　key:sws_flags/value:spline+accurate_rnd+full_chroma_int
再起動後　　　　key:1/value:sws_flags,spline+accurate_rnd+full_chroma_int

動作環境:Windows 11 Home 24H2 26100.2454

**Comment by xpadev-net** [comment]
報告ありがとうございます
#114 の方で対応しましたので、次回リリース時に修正が反映されるかと思います
