### ISSUE TITLE
コマンドラインからのGUIを介さない実行

### ISSUE THREAD

**Issue by raibonn** [xpadev-net/niconicomments-convert#112]
本プロジェクトをコマンドラインからの実行を可能にしてはどうでしょうか。
CUIから実行できるようにする。またはCUI版を用意することで，プラットフォームに依存せずに柔軟に使用でき(Linux等からも)，
また，別プログラム等に組み込みやすくなるのではないかと考えました。

**Comment by xpadev-net** [comment]
このアプリケーションはレンダリング周りの実装をelectronに依存しており、仮にヘッドレス対応を行うとなるとある程度改修が必要になると見込まれることから現時点でヘッドレス対応は検討していません

Linux対応は可能ですがこちらについても利用者がそこまで居ないと思われるため検討していません

何かしら他のプログラムに組み込むことを検討されているようであれば描画ライブラリである [xpadev-net/niconicomments](https://github.com/xpadev-net/niconicomments) を直接使用されることをおすすめします
