### ISSUE TITLE
一部動画の変換がエラーにより出来ない

### ISSUE THREAD

**Issue by TONKOTSU-UDON** [xpadev-net/niconicomments-convert#16]
先日、0.0.12において動画を変換しようとしたところ、ある動画の変換が出来ずエラーを吐きます。
しかし、結構前にダウンロードした動画とXMLファイルでは変換が出来たので、今回コメントと動画をダウンロードする際に使用したniconicome側の仕様変更のせいである可能性も高いので、私側のミスだった場合申し訳ありません

使用した動画
[sm42756410](https://www.nicovideo.jp/watch/sm42756410)
こちらの動画とコメントをniconicome-v0.13.3でダウンロード。
二つの動画を選択し変換を開始しようとしたところ下記のエラーが出て変換が出来ませんでした。

```
未知のエラーが発生しました
未知のIPCメッセージを受信しました
{
	"type": "message",
	"title": "未知のエラーが発生しました",
	"message": "エラー内容：\n{}",
	"host": "renderer"
}
```
niconicomments convert側の設定は
・60fps
・当たり判定表示、コメント描画数表示、CA衝突抑制 全て無し
・スケール１
・変換モード 自動

使用した動画
![スクリーンショット](https://github.com/xpadev-net/niconicomments-convert/assets/95231657/8770b78c-0943-4a21-81f4-0f5e62abb545)

また、以前報告させていただいた認証タブが機能しない点についてですが、今回変換しようとしたときにもう一度試したところ次のようなエラー文が出力されました。ユーザー名は個人名だったので伏せてあります。ユーザー名は半角英数字です。
```
予期しないエラーが発生しました
エラー内容:
{
	"errno": -4082,
	"syscall": "copyfile",
	"code": "EBUSY",
	"path": "C:\\Users\\ユーザー名\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies",
	"dest": "C:\\Users\\ユーザー名\\AppData\\Local\\Temp\\niconicomments-convert\\Cookies"
}
```

使用しているPC
・OS windows10 
・バージョン 22H2

**Comment by xpadev-net** [comment]
> 先日、0.0.12において動画を変換しようとしたところ、ある動画の変換が出来ずエラーを吐きます。

こちら手元の環境で試してみたところ問題なくダウンロードできたため、-convert内臓のコメントダウンロード機能を使用して見てください※ログイン必須です

>また、以前報告させていただいた認証タブが機能しない点についてですが、今回変換しようとしたときにもう一度試したところ次のようなエラー文が出力されました。ユーザー名は個人名だったので伏せてあります。ユーザー名は半角英数字です。

こちらについてですが、Chrome114からChromeの起動中に他のプロセスからCookieを読み取れないように変更されたらしく、それが原因だと思われます
一旦ブラウザを停止して試してみてください

**Comment by TONKOTSU-UDON** [comment]
> こちらについてですが、Chrome114からChromeの起動中に他のプロセスからCookieを読み取れないように変更されたらしく、それが原因だと思われます
一旦ブラウザを停止して試してみてください

chromeを完全に停止し、他のブラウザも起動していない状態で設定画面を開きましたが、
```
予期しないエラーが発生しました
エラー内容:
{}
```
というエラーが出ます。そこからブラウザから取得ボタンを押しても暗転するだけで何も起こりません(cookieから取得は選択できない)
バックグラウンドでも動いていないので停止はできているはずです。

**Comment by TONKOTSU-UDON** [comment]
私はニコニコのアカウントに二段階認証を設定しているのですが、二段階認証を設定しているせいでエラーが出ている可能性はありますか？セキュリティ対策として利用しておりましたが、もしその可能性が高そうであれば一度解除して検証してみようと思います。

**Comment by xpadev-net** [comment]
認証を行う際のブラウザからcookieを読み込む段階でエラーが出ているため二段階認証は特に関係ないかと思います
対策を考えるのでしばらく待ってもらえるとありがたいです

**Comment by TONKOTSU-UDON** [comment]
分かりました！！多分ここで詰まってるのは私だけだと思うのでお手数おかけして申し訳ありません；；

**Comment by xpadev-net** [comment]
Cookie取得で落ちる不具合についてはv0.0.13で対応済みです
