### ISSUE TITLE
[質問] 変換時に指定するFPSについて

### ISSUE THREAD

**Issue by TONKOTSU-UDON** [xpadev-net/niconicomments-convert#19]
動画とコメントを選択した後FPSを入れる欄があると思いますが、この数値は選択した動画が30FPSの場合、60fpsに指定するとどのような挙動になりますか？コメントのみが60fps化されるということでしょうか。

また、FPS値の上限などはありますか？コメントの挙動を滑らかにしようと120や200など、高い数値に設定したいのですがイマイチ変わっているように思えません。30、または60が上限なのでしょうか。

**Comment by xpadev-net** [comment]
現在リリースされている最新版だと動画のFPSが上限値になります
これについては修正を行っていますがまだリリースできていないので、次のリリースまでは元動画のFPSを引き上げてから変換にかけるなどして対応してもらえるとありがたいです

**Comment by TONKOTSU-UDON** [comment]
わかりました！ありがとうございます！
