### ISSUE TITLE
ニコ生のギフト、エモーション、アンケート機能の対応

### ISSUE THREAD

**Issue by nnn-revo2012** [xpadev-net/niconicomments-convert#6]
このツールってニコ生のギフト、エモーション、アンケート機能のようなニコ生独自の機能には対応してるんですか？

**Comment by xpadev-net** [comment]
もとのniconicommentsがニコニコ動画互換を目指して作成しているためニコ生独自機能には対応していません
需要があるようであればニコ生互換機能も検討しますが、現状はニワン語対応の方に労力を割いているため結構先の方になるかと思います

**Comment by nnn-revo2012** [comment]
ご回答ありがとうございまいた。
