### ISSUE TITLE
設定の変換のkey欄を書き換えようとすると変な事になる

### ISSUE THREAD

**Issue by Helium745** [xpadev-net/niconicomments-convert#84]
一番下を書き換える分には問題はないですが、途中を書き換えようとすると、
入力位置は変わらずにその箇所が一番下に移動します。
また、value欄を書き換えても同じような問題ありません。

**Comment by xpadev-net** [comment]
報告ありがとうございます
原因の目星はついたので近いうちに修正を行います 🙇‍♂️
