### ISSUE TITLE
コメントをダウンロードする際に動画情報の取得に失敗する

### ISSUE THREAD

**Issue by TONKOTSU-UDON** [xpadev-net/niconicomments-convert#93]
コメントをダウンロードしようとしたところ、「動画情報の取得に失敗しました 未購入の有料動画などの可能性があります」と表示されダウンロードできませんでした。
使用した動画はこちらです。
https://www.nicovideo.jp/watch/sm43537763
https://www.nicovideo.jp/watch/sm43531949

しかし、ダウンロードできる動画も中にはあり下記の動画はコメント取得に成功しました。
https://www.nicovideo.jp/watch/sm43386941
https://www.nicovideo.jp/watch/sm39517909

投稿されてから日が浅いと取得できない仕様でしょうか？また、コメントをダウンロードする際に表示される「カスタム」が常時灰色ですがこれはどういったものになるのでしょうか。

**Comment by xpadev-net** [comment]
- コメントのダウンロードについて
dmcに動画がない動画をコメントダウンロード時に弾いていたためdmsのみの動画でエラーになっていました

- 「カスタム」について
[wiki](https://github.com/xpadev-net/niconicomments-convert/wiki/%E5%8B%95%E7%94%BB%E3%83%BB%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AE%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89#%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AE%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89)の参照をお願いします

**Comment by TONKOTSU-UDON** [comment]
ありがとうございます！お恥ずかしながらwikiが更新されていることに今気づきましたので隅から隅まで読んできます。。。
